spring:
  datasource:
    url: jdbc:mysql://localhost:3306/userauthenticationsystem?serverTimezone=UTC&characterEncoding=UTF-8
    username: 'root'
    password: '0000'

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        dialect: org.hibernate.dialect.MySQLDialect

  thymeleaf:
    cache: false
